# Generated by Django 5.0.6 on 2024-07-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0004_about_sociallink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="link",
            field=models.URLField(max_length=100),
        ),
    ]
